I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 228, in script
    show Kitty_sprite standing at sprite_location(0.25)
Exception: DynamicImage u'images/Kitty_standing/Kitty_standing_spunk_mouth[KittyX.mouth].png': could not find image. (u'images/Kitty_standing/Kitty_standing_spunk_mouth_smirk.png')

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 228, in script
    show Kitty_sprite standing at sprite_location(0.25)
  File "renpy/ast.py", line 1197, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1167, in show_imspec
    atl=atl)
  File "renpy/exports.py", line 768, in show
    sls.add(layer, img, key, zorder, behind, at_list=at_list, name=name, atl=atl, default_transform=default_transform, transient=transient)
  File "renpy/display/core.py", line 1147, in add
    thing.visit_all(lambda d : None)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 558, in visit_all
    for d in self.visit():
  File "renpy/display/layout.py", line 1415, in visit
    self.update(self.last_st, self.last_at)
  File "renpy/display/layout.py", line 1443, in update
    child.visit_all(lambda c : c.per_interact())
  File "renpy/display/core.py", line 558, in visit_all
    for d in self.visit():
  File "renpy/display/image.py", line 744, in visit
    self.find_target()
  File "renpy/display/image.py", line 652, in find_target
    raise Exception(error)
Exception: DynamicImage u'images/Kitty_standing/Kitty_standing_spunk_mouth[KittyX.mouth].png': could not find image. (u'images/Kitty_standing/Kitty_standing_spunk_mouth_smirk.png')

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Rogue-Like Chonky Mod 0.2h
Mon Jun 20 21:42:54 2022
