I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/locations.rpy", line 132, in script call
    call world_map
  File "game/locations.rpy", line 610, in script call
    call world_map
  File "game/locations.rpy", line 610, in script call
    call world_map
  File "game/locations.rpy", line 132, in script call
    call world_map
  File "game/locations.rpy", line 709, in script call
    call world_map
  File "game/locations.rpy", line 132, in script call
    call world_map
  File "game/locations.rpy", line 325, in script call
    call set_the_scene
  File "game/utilities.rpy", line 730, in script
    return
Exception: Could not find return label (u'game/utilities.rpy', 1653339557, 3).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/locations.rpy", line 132, in script call
    call world_map
  File "game/locations.rpy", line 610, in script call
    call world_map
  File "game/locations.rpy", line 610, in script call
    call world_map
  File "game/locations.rpy", line 132, in script call
    call world_map
  File "game/locations.rpy", line 709, in script call
    call world_map
  File "game/locations.rpy", line 132, in script call
    call world_map
  File "game/locations.rpy", line 325, in script call
    call set_the_scene
  File "game/utilities.rpy", line 730, in script
    return
  File "renpy/ast.py", line 1567, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "renpy/execution.py", line 710, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'game/utilities.rpy', 1653339557, 3).

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Rogue-Like 0.997f2
Tue May 24 00:59:57 2022
